### ISSUE TITLE
#007 clear board 이벤트를 추가한다

### ISSUE THREAD

**Issue by warmwhiten** [TeamScramble/scramble_server#11]
### Description
- @GyuhoLee 이전에 notion에서 요청 부탁드린 clear board 이벤트 추가 부탁드립니다.
- clear board를 따로 추가하지 않고 drawing 이벤트로 보내되, 함께 전송하는 데이터를 다르게 하여 클라이언트 측에서 이를 구분하도록 구현하는 것도 좋을 것 같습니다. 구현 방법에 대해서는 규호님께서 두 가지 방법 모두 고려해보시고 설계상 더 나은 방향으로 진행하시면 될 것 같습니다.
- 관련해서 논의가 필요하시면 편하게 요청해주세요. 

감사합니다.

**Comment by GyuhoLee** [comment]
클라이언트에서 drawing이 보드의 값에 추가로 덧붙이는 작업이라면, 전자가 나은 것 같고 기존 보드의 그림과 추가된 내용을 모두 담는 방식이라면 drawing 하나로 해결할 수 있을 것 같습니다.
다만, board의 내용을 모두 지우는 이벤트는 특정 버튼을 클릭하면 수행되는 작업이니 상관없이 이벤트로 구분하는 것도 좋아보이네요. 저는 상관 없으니 다희님 편한대로 오더해주세요
